config/routes.rb
Rails.application.routes.draw do

  resources :likes, except: [:destroy, :update, :create, :edit]
  post 'like/:article_id', to: 'likes#like'
  get 'like/:id', to: 'likes#show'

  resources :favorites, except: [:destroy, :update, :create, :edit]
  post 'favorite/:article_id', to: 'favorites#favorite'
  get 'favorites/:id', to: 'favorites#show'

  devise_for :users

  resources :articles do
    resources :comments
  end

  resources :profiles, only: [:show]

  root 'articles#index'
  get 'filter_articles', to: 'articles#filter_articles'

end

app/models/article.rb
class Article < ApplicationRecord
  has_many :likes, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  belongs_to :user
  validates_format_of :img_url, with: %r{\.(png|jpg|jpeg)\z}i, message: "Please provide a valid image."
  validates :description, length: {minimum: 1, maximum: 200}
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    @article.user_id = current_user.id
    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  #Used by _search partial.
  #Params: filter_by - used to identify the searching method.
  def filter_articles

      search_query = params[:search_query]
      filter_method = params[:filter_method]

      @articles = []

      #possibly % %
      if filter_method == "0"
        @articles = Article.where('title LIKE ?', "%#{search_query}%")
      elsif filter_method == "1"

        user_likes = Favorite.where(user_id: current_user.id)
        liked_articles = []

        #Find all of the favorited articles
        user_likes.each do |like|
          liked_articles << Article.find(like.article_id)
        end

        #Add the article only if its title contains the search query string
        liked_articles.each do |article|
          @articles << article if article.title.include? search_query
        end

      elsif filter_method == "2"

        user_favorites = Favorite.where(user_id: current_user.id)
        favorited_articles = []

        #Find all of the favorited articles
        user_favorites.each do |favorite|
          favorited_articles << Article.find(favorite.article_id)
        end

        #Add the article only if its title contains the search query string
        favorited_articles.each do |article|
          @articles << article if article.title.include? search_query
        end

      else
      end

      respond_to do |format|
        format.js{}
      end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :description, :img_url, :user_id)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: @article, local: true) do |form| %>

<%= render 'common/error_messages', object: @article %>

<div class="form-group">
  <%= form.label :title, class:"form-label" %>
  <%= form.text_field :title, id: :title, class:"form-control" %>
</div>

<div class="form-group">
  <%= form.label :description, class:"form-label" %>
  <%= form.text_area :description, id: :article_description, class:"form-control", rows: 5 %>
</div>

<div class="form-group">
  <%= form.label :img_url, class:"form-label" %>
  <%= form.text_field :img_url, id: :article_img_url, class:"form-control" %>
</div>

<%= form.submit class:"btn btn-lg btn-success" %>

<% end %>

app/views/articles/edit.html.erb
<h1>Edit <%= @article.title %></h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/filter_articles.js.erb
$('#articles').html("<%= j render 'common/list_user_posts', articles: @articles %>");

//See favorites.js.erb/likes.js.erb for explanation
bindLikeButtons();
bindFavoriteButtons();

app/views/articles/index.html.erb
<div class="container text-center">

<% if user_signed_in? %>

<h2 class="text-center field-margin-md">Search Posts</h1>
  <!-- In future: make filter_method 0 more elegant -->
<%= render 'common/search', {articles:@articles, filter_method:0} %>

<div id="articles">
  <%= render 'common/list_user_posts', articles: @articles %>
</div>

</div>

<%else%>

<%= render 'common/welcome_page' %>

<%end%>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<div class="container well text-center field-margin-lg">

<h2><%= @article.title %></h2>

<img src="<%=@article.img_url %>" alt="Post image" class="post-image img-responsive img-rounded">


<p class = "post-field">
  <%= @article.description %>
</p>

<p class = "post-field">
  <span class="label label-success">Posted by:</span>
  <i class="fa fa-user-o" aria-hidden="true"></i>
  <%= link_to @article.user.email, profile_path(@article.user_id)%>
</p>

<% if current_user.id == @article.user_id %>
<span class="label label-success"><%= link_to 'Edit', edit_article_path(@article), style:"color:white" %></span>
<span class="label label-danger"><%= link_to 'Delete', @article, method: :delete, data: { confirm: 'Are you sure?' }, style:"color:white" %></span>
<%end%>

</div>

<div class="container well text-center">

  <%= render 'comments/form', {comment: Comment.new, article_id: @article.id} %>
  <span class="field-margin-lg"></span>
  <%= render 'comments/list_all_comments', comments: @article.comments %>

</div>