config/routes.rb
Rails.application.routes.draw do

  resources :likes, except: [:destroy, :update, :create, :edit]
  post 'like/:article_id', to: 'likes#like'
  get 'like/:id', to: 'likes#show'

  resources :favorites, except: [:destroy, :update, :create, :edit]
  post 'favorite/:article_id', to: 'favorites#favorite'
  get 'favorites/:id', to: 'favorites#show'

  devise_for :users

  resources :articles do
    resources :comments
  end

  resources :profiles, only: [:show]

  root 'articles#index'
  get 'filter_articles', to: 'articles#filter_articles'

end

app/views/common/_error_messages.html.erb
<% if object.errors.any? %>

<%= object.errors.full_messages.each do |message| %>
<div class="alert alert-danger" role="alert">
  <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
  <span class="sr-only">Error:</span>
  <%=message%>
</div>

<%end%>

<%end%>

app/views/common/_like_favorite.html.erb
<div class="form-inline field-margin-sm">
  <a class="label label-success like_button" style="font-size:14px">
     <%if current_user.likes.where(article_id: article).empty? %>
     <i class="fa fa-thumbs-o-up" aria-hidden="true">Like</i>
     <%else%>
     <i class="fa fa-thumbs-up" aria-hidden="true">Unlike</i>
     <%end%>
  </a>
  <a class="label label-warning favorite_button" style="font-size:14px">
    <%if current_user.favorites.where(article_id: article).empty? %>
    <i class="fa fa-heart-o" aria-hidden="true">Favorite</i>
    <%else%>
    <i class="fa fa-heart" aria-hidden="true">Unfavorite</i>
    <%end%>
  </a>
</div>
<div class="stat_labels form-inline field-margin-sm">
  <p class="like_label"><i class="fa fa-thumbs-up field-margin-xs" aria-hidden="true"></i>   Likes: <%= article.likes.count%></p>
  <p class="favorite_label"><i class="fa fa-heart" aria-hidden="true"></i>   Favorites: <%= article.favorites.count%></p>
</div>
<%= hidden_field_tag(:article_id, value = article.id, class: "article_id") %>

app/views/common/_list_user_posts.html.erb
<div class="post">

  <div class="wow fadeIn">

  <label class="label label-success" style="font-size:17px"><%= articles.count %> Posts Found</label>

  <% if articles.count != 0 %>
    <% articles.each do |article| %>
      <div class="row field-margin-sm">
      <div class="col-sm-12">

      <div class="container text-center well post-index-entry" style="width:80%">

              <h2><%= article.title %></h2>

              <img src="<%=article.img_url %>" alt="Post image" class="post-image-index img-responsive img-rounded">

              <!-- Render the like and favorite partial -->
              <%= render 'common/like_favorite', article: article %>

              <p class ="field-margin-sm">
                <%= article.description %>
              </p>

              <p class="field-margin-sm">
                <span class="label label-success">Posted by:</span>
                <i class="fa fa-user-o" aria-hidden="true"></i>
                <%= link_to article.user.email, profile_path(article.user_id)%>
              </p>

              <span class="label label-primary"><%= link_to 'Show', article, style:"color:white" %></span>
              <% if current_user.id == article.user_id %>
              <span class="label label-success"><%= link_to 'Edit', edit_article_path(article.id), style:"color:white" %></span>
              <span class="label label-danger"><%= link_to 'Delete', article, method: :delete, data: { confirm: 'Are you sure?' }, style:"color:white" %></span>
              <%end%>

        </div>
      </div>
      </div>
    <% end %>
  <% else %>
    <div class="alert alert-warning" role="alert">
      <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
      <span class="sr-only">Warning</span>
      No posts found. Please try a different title.
    </div>
  <% end %>

  </div>

</div>

app/views/common/_search.html.erb
  <div class="container field-margin-md">

    <div class="row text-center" >
      <div class="col-sm-offset-2 col-sm-7">
        <%= form_with url: filter_articles_path, id:"search_form", method: :get do |form| %>
            <div class="row">
              <div class="col-6">
                <div class="input-group">
                  <span class="input-group-btn">
                    <button id="search_btn" class="btn btn-default" type="button"><i class="fa fa-search" aria-hidden="true"></i></button>
                  </span>
                  <%= form.text_field :search_query, id: 'search_field', class:'form-control', placeholder:"Search posts..." %>
                  <%= form.hidden_field :filter_method, value: filter_method %>
                </div><!-- /input-group -->
              </div><!-- /.col-lg-6 -->
            </div>
        <%end%>
      </div>
    </div>

  </div>

  <h2 class="text-center field-margin-md">User Posts</h1>

app/views/common/_welcome_page.html.erb
<div class="container-fluid">
  <div class="jumbotron welcome-page-head">
      <h1 class="field-margin-lg">Welcome to Nutz - The IG for Squirrels!</h1>
      <h2 class=" field-margin-lg">Please sign up to get started; or log in if you're an existing user.</h2>
      <div class="form-inline">
        <%= link_to 'Sign-up', new_user_registration_path, class: "btn btn-success btn-lg", style:"color:white" %>
        <%= link_to 'Log-in', new_user_session_path, class: "btn btn-success btn-lg", style:"color:white" %>
      </div>
  </div>
</div>