config/routes.rb
Rails.application.routes.draw do

  resources :likes, except: [:destroy, :update, :create, :edit]
  post 'like/:article_id', to: 'likes#like'
  get 'like/:id', to: 'likes#show'

  resources :favorites, except: [:destroy, :update, :create, :edit]
  post 'favorite/:article_id', to: 'favorites#favorite'
  get 'favorites/:id', to: 'favorites#show'

  devise_for :users

  resources :articles do
    resources :comments
  end

  resources :profiles, only: [:show]

  root 'articles#index'
  get 'filter_articles', to: 'articles#filter_articles'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Nutz" %></title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag "application", :media => "all" %>

  <%= javascript_include_tag "application" %>

  <script src="https://use.fontawesome.com/3df3601870.js"></script>
  <script>new WOW().init();</script>
  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
  <![endif]-->
</head>
<body>

  <div class="navbar navbar-default navbar-static-top">
    <div class="container">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="/" class="navbar-left"><img src='<%=image_url('icon.png')%>' alt="Nutz - the Squirrel Network" class="navbar-brand"></a>
      <div class="navbar-collapse collapse navbar-responsive-collapse">
        <ul class="nav navbar-nav">
          <% if user_signed_in? %>
          <div class="dropdown">
            <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
              Actions
              <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
              <li><%= link_to "Create new post", new_article_path  %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "View liked posts", like_path(current_user.id)  %></li>
              <li><%= link_to "View favorited posts", favorite_path(current_user.id)  %></li>
            </ul>
          </div>
          <%end%>
        </ul>
        <% if user_signed_in? %>
          <div class="navbar navbar-right"><%= link_to 'Log-out', destroy_user_session_path, method: :delete %></div>
        <%else%>
          <div class="navbar navbar-right" style="margin-left:15px"><%= link_to 'Log-in', new_user_session_path %></div>
          <div class="navbar navbar-right"><%= link_to 'Sign up', new_user_registration_path %></div>
        <%end%>
      </div>

    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-lg-9">
        <%= bootstrap_flash %>
        <%= yield %>

        <footer>
          <p>&copy; JC Software 2017</p>
        </footer>

      </div> <!-- /container -->

    </body>
    </html>